export const Projects = [
  {
    _id: "0",
    type: "Web Developement",
    tittle: "Project Center Website",
    built: "Built - Next Js | MongoDB | Material UI | Redux",
    link: "https://lucky-six.vercel.app/",
    img: require("../public/luckychamp.jpg"),
  },
  {
    _id: "1",
    type: "Web Developement",
    tittle: "Shopping Website",
    built: "Built - React Js | Supabase | Material UI",
    link: "https://shoping-todolist-auth.vercel.app/Loginpage",
    img: require("../public/shopping.jpeg"),
  },
  {
    _id: "2",
    type: "Web Developement",
    tittle: "To-Do-List",
    built: "Built - React Js | MongoDB | Tailwind",
    link: "https://crudapi-f8ce-imckyutly-gokul-pga.vercel.app/",
    img: require("../public/CRUD.jpg"),
  },
  {
    _id: "3",
    type: "Web Developement",
    tittle: "Resume Shortlist",
    built: "Built - Next Js | MongoDB | Tailwind",
    link: "https://nextjob.pages.dev/",
    img: require("../public/NxtJob.jpg"),
  },
  {
    _id: "4",
    type: "Web Developement",
    tittle: "Gallery-Website",
    built: "Built - Next Js | MongoDB | Tailwind",
    link: "https://gallery-fyas.vercel.app/",
    img: require("../public/Gallery.jpg"),
  },
];
